---
- name: Добавление GPG ключа Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Добавление репозитория Kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes

- name: Установка компонентов Kubernetes
  apt:
    name:
      - kubelet={{ kubernetes_version }}
      - kubeadm={{ kubernetes_version }}
      - kubectl={{ kubernetes_version }}
    state: present
    update_cache: yes

- name: Отключение swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Удаление swap из /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: Загрузка модулей ядра
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
    - overlay
    - br_netfilter

- name: Настройка параметров ядра
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: yes
    sysctl_file: /etc/sysctl.d/k8s.conf
    reload: yes
  with_items:
    - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }
    - { name: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
    - { name: 'net.ipv4.ip_forward', value: '1' }

- name: Создание конфигурации kubeadm
  template:
    src: kubeadm-config.yaml.j2
    dest: /tmp/kubeadm-config.yaml
  when: inventory_hostname in groups['k8s_masters']

- name: Инициализация кластера Kubernetes
  command: kubeadm init --config=/tmp/kubeadm-config.yaml
  when: inventory_hostname in groups['k8s_masters']

- name: Создание .kube директории
  file:
    path: /root/.kube
    state: directory
    mode: '0755'
  when: inventory_hostname in groups['k8s_masters']

- name: Копирование admin.conf
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    remote_src: yes
    mode: '0644'
  when: inventory_hostname in groups['k8s_masters']

- name: Установка CNI плагина
  command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
  when: inventory_hostname in groups['k8s_masters']

- name: Получение join команды
  command: kubeadm token create --print-join-command
  register: join_command
  when: inventory_hostname in groups['k8s_masters']

- name: Присоединение worker нод к кластеру
  command: "{{ join_command.stdout }}"
  when: inventory_hostname in groups['k8s_workers'] 