---
# Роль ноды
node_role: kubernetes

# Настройки сети (уже настроены в Ubuntu)
network_interface: ens33
network_netmask: 255.255.255.0
network_gateway: 192.168.1.1

# Настройки Kubernetes
kubernetes_enabled: true
kubelet_enabled: true
kubeadm_enabled: true

# Метки ноды
node_labels:
  role: kubernetes
  type: k8s

# Настройки ресурсов (уже выделены в ВМ)
resources:
  cpu: "2"
  memory: "4Gi"
  storage: "30Gi"

# Настройки Docker
docker_version: "20.10.23"
container_runtime: containerd

# Настройки для уже существующих ВМ
existing_vm: true 