---
# Роль ноды
node_role: kubernetes

# Настройки Kubernetes
kubernetes_enabled: true
kubelet_enabled: true
kubeadm_enabled: true

# Метки ноды
node_labels:
  role: kubernetes
  type: k8s

# Настройки ресурсов (уже выделены в ВМ)
resources:
  cpu: "3"
  memory: "3Gi"
  storage: "20Gi"

# Настройки Docker
docker_version: "20.10.23"
container_runtime: containerd

# Настройки для уже существующих ВМ
existing_vm: true

# IP-адреса Kubernetes
k8s-node-1 ansible_host=10.0.2.7
k8s-node-2 ansible_host=10.0.2.11 